-- Apollo+ Upgrade: Aging, Escalation, SLA, Denial Analytics, Audit Trail

ALTER TABLE master_tpa ADD COLUMN IF NOT EXISTS sla_days INT DEFAULT 30, ADD COLUMN IF NOT EXISTS sla_days_preauth INT DEFAULT 5;

ALTER TABLE insurance_claim_master ADD COLUMN IF NOT EXISTS aging_days INT, ADD COLUMN IF NOT EXISTS aging_bucket VARCHAR(20), ADD COLUMN IF NOT EXISTS sla_due_date DATE, ADD COLUMN IF NOT EXISTS is_sla_breached BOOLEAN DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS master_escalation_role (escalation_role_id BIGINT PRIMARY KEY AUTO_INCREMENT, role_name VARCHAR(100) UNIQUE NOT NULL, escalation_level INT DEFAULT 1, is_active BOOLEAN DEFAULT TRUE);

CREATE TABLE IF NOT EXISTS insurance_claim_escalation (escalation_id BIGINT PRIMARY KEY AUTO_INCREMENT, claim_id BIGINT NOT NULL, escalation_level INT NOT NULL, escalation_to_role_id BIGINT NULL, escalation_due_date DATE NOT NULL, escalated_at DATETIME DEFAULT CURRENT_TIMESTAMP, escalated_by BIGINT, remarks TEXT, acknowledged_at DATETIME NULL, acknowledged_by BIGINT NULL, resolution_remarks TEXT, FOREIGN KEY (claim_id) REFERENCES insurance_claim_master(claim_id), FOREIGN KEY (escalation_to_role_id) REFERENCES master_escalation_role(escalation_role_id));

CREATE TABLE IF NOT EXISTS insurance_claim_denial_analytics (analytics_id BIGINT PRIMARY KEY AUTO_INCREMENT, rejection_reason_id BIGINT NOT NULL, insurance_company_id BIGINT NOT NULL, department_id BIGINT NULL, month_year VARCHAR(7) NOT NULL, denial_count INT DEFAULT 0, total_rejected_amount DECIMAL(14,2) DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (rejection_reason_id) REFERENCES master_claim_rejection_reason(rejection_reason_id), FOREIGN KEY (insurance_company_id) REFERENCES master_insurance_company(insurance_company_id), UNIQUE KEY uk_denial (rejection_reason_id, insurance_company_id, department_id, month_year));

CREATE TABLE IF NOT EXISTS insurance_claim_audit_log (audit_id BIGINT PRIMARY KEY AUTO_INCREMENT, claim_id BIGINT NOT NULL, old_status_id BIGINT NULL, new_status_id BIGINT NOT NULL, old_status_name VARCHAR(50), new_status_name VARCHAR(50), changed_by BIGINT, changed_at DATETIME DEFAULT CURRENT_TIMESTAMP, ip_address VARCHAR(45), remarks TEXT, FOREIGN KEY (claim_id) REFERENCES insurance_claim_master(claim_id), FOREIGN KEY (old_status_id) REFERENCES master_claim_status(claim_status_id), FOREIGN KEY (new_status_id) REFERENCES master_claim_status(claim_status_id));

CREATE OR REPLACE VIEW v_insurance_claim_aging_summary AS SELECT cm.claim_id, cm.claim_number, cm.claim_amount, cm.approved_amount, cm.settled_amount, cm.submitted_at, cs.status_name AS claim_status, DATEDIFF(NOW(), cm.submitted_at) AS aging_days_calc, CASE WHEN DATEDIFF(NOW(), cm.submitted_at)<=30 THEN '0-30' WHEN DATEDIFF(NOW(), cm.submitted_at)<=60 THEN '31-60' WHEN DATEDIFF(NOW(), cm.submitted_at)<=90 THEN '61-90' ELSE '90+' END AS aging_bucket_calc, cm.aging_days, cm.aging_bucket, cm.sla_due_date, cm.is_sla_breached, a.admission_no, p.uhid, ic.company_name FROM insurance_claim_master cm LEFT JOIN master_claim_status cs ON cm.claim_status_id=cs.claim_status_id LEFT JOIN ipd_admission_master a ON cm.ipd_admission_id=a.ipd_admission_id LEFT JOIN patient_master p ON a.patient_id=p.patient_id LEFT JOIN master_insurance_company ic ON cm.insurance_company_id=ic.insurance_company_id WHERE cm.submitted_at IS NOT NULL;
